export const data = [
  {
    id: 1,
    text: "HQD MANGO ICE 3% + ВТОРОЙ ЭТАЖ ЗАПАСНОЙ",
    price: 950,
    count: "НАЛИЧИЕ: 1000 ШТ",
    apt: "АРТ.: ART-6 945",
    changed_count: 1,
    image: require("./components/images/puff1.png"),
  },
  {
    id: 2,
    text: "HQD MANGO ICE 3% + ВТОРОЙ ЭТАЖ ЗАПАСНОЙ",
    price: 950,
    count: "НАЛИЧИЕ: 1000 ШТ",
    apt: "АРТ.: ART-6 945",
    changed_count: 1,
    image: require("./components/images/puff1.png"),
  },
  {
    id: 3,
    text: "HQD MANGO ICE 3% + ВТОРОЙ ЭТАЖ ЗАПАСНОЙ",
    price: 950,
    count: "НАЛИЧИЕ: 1000 ШТ",
    apt: "АРТ.: ART-6 945",
    changed_count: 1,
    image: require("./components/images/puff3.png"),
  },
  {
    id: 4,
    text: "HQD MANGO ICE 3% + ВТОРОЙ ЭТАЖ ЗАПАСНОЙ",
    price: 950,
    count: "НАЛИЧИЕ: 1000 ШТ",
    apt: "АРТ.: ART-6 945",
    changed_count: 1,
    image: require("./components/images/puff4.png"),
  },
  {
    id: 5,
    text: "HQD MANGO ICE 3% + ВТОРОЙ ЭТАЖ ЗАПАСНОЙ",
    price: 950,
    count: "НАЛИЧИЕ: 1000 ШТ",
    apt: "АРТ.: ART-6 945",
    changed_count: 1,
    image: require("./components/images/puff4.png"),
  },
];
